### ISSUE TITLE
Gem installation

### ISSUE THREAD

**Issue by rbock** [douyw/sqlpp11gen#1]
Hi,

are you planning to make the gem installation work?

Would you like to get your script linked from the sqlpp11 project?

Best,

Roland

**Comment by douyw** [comment]
The gem version had been published. It's [here](https://rubygems.org/gems/sqlpp11gen). Please report or fix if any problem exists.

Of course yes. Please link it, it's great! Thank you!

**Comment by rbock** [comment]
I finally added the link. Sorry for taking so long.
